language: perl

perl:
   - "5.22"
   - "5.20"
   - "5.18"
   - "5.16"
   - "5.14"
   - "5.12"
   - "5.10"
   - "5.8"

# Use the container-base Travis infrastructure
sudo: false

notifications:
   on_success: change
   on_failure: always
   irc:
      channels:
         - "irc.perl.org#perlcritic"
      template:
         - "%{branch}: %{message} %{build_url}"

addons:
  apt:
    packages:
    - aspell
    - aspell-en

install:
   - cpanm Perl::Critic::More Test::Perl::Critic Devel::EnforceEncapsulation

script:
   - export HARNESS_OPTIONS='j:c'
   - perl Build.PL
   - ./Build authortest
